on:
  push:
    branches:
      - main
  pull_request:

name: Build - Verified CRDT 
jobs:
  runidris:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v19
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell
      - run: nix-shell --command "idris2 --build crdt.ipkg"