on:
  push:
    branches:
      - main
  pull_request:

name: Verified CRDT Build
jobs:
  runidris:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v19
        env:
          NIX_CONFIG: "experimental-features = nix-command flakes"
      - run: nix build
